late_job: "Freelance developer (Arbousier.info)"
toys:
  - RubyOnRails
  - ZeroMQ
  - Redis
  - Rackspace
  - Heroku
  - Carrierwave
  - Resque
  - Thor
  - Debian
  - PacketFilter
  - CSS3
  - JQuery
  - Sinatra
  - Padrino
  - Git
  - Perl
  - MongoDB
  - PostgreSQL
  - MySQL
  - ThreePanelSoul & MacHall
  - Gentoo
  - OpenBSD
  - NetBSD
  - FreeBSD
  - Nginx
  - Xen
  - Kvm
  - Bind
  - Magic The Gathering
  - Cthulhu
involved:
  - "TauCW (a coworking project)"
  - "Toulouse.rb (a local Ruby group)"
  - "GCU.info (french *BSD and GNU/Linux developpers and users chaotic group)"
  - "Libr'East (two days technical event)"
future:
  - Beer brewing
  - Ruby + 0MQ + Redis (at the same time)
  - Erlang
  - Coffeescript
  - Puppet and Chef
  - God and Munit
games:
  Edo: "https://github.com/mcansky/Edo-script"
  Mjölk: "https://github.com/mcansky/mjolk"
  XiRisH.rb: "https://github.com/mcansky/XiRisH.rb"
  presslang: "https://github.com/mcansky/presslang"
  gaze: "https://github.com/mcansky/gaze"
  IIIaquarii: "https://github.com/rhaamo/IIIaquarii"
past:
  - "I didn't managed to get to Mordor with my loyal dog disguised as Sam sometime around @4, ended up eating cherries in a notsofarawayfromhome piece of land"
  - "I've read tons of books and lived in a castle with snakes, rabbits and howls surrounding it (@4 -> @17yo)"
  - "Somehow found myself with a Apple Mac SE in front of me (@6) didn't do much with it"
  - "I've put servers together for my father's company and started to play with something called Linux (@17)"
  - "I've started an Electronic and Computer degree, and decided to go for a Digital Audiovisual Systems specialisation (@17 -> @22)"
  - "I've organised two days of technical talks with some other OpenSource devs and managed to get lots of people coming (@21)"
  - "I've played with Php, Delphi, TCP/IP and XML for the biggest french TV channel and got my diploma (@22)"
  - "I've played hide and seek with 3k+ lines of KSH script (a single one) on RedHat Linux, Solaris, and AIX systems and their packaging system for a consulting company (@23)"
  - "I've worked for O'Reilly Ed to proof read technical examples' translations in books (@25)"
  - "I've rode a Dragon twice and survived to talk about it (@24 and @25)"
  - "I've planted trees, night managed a backpacker/hostel, cleaned up bins at a Formula 1 Grand Prix, hiked a beautiful park in Australia (@25)"
  - "I've written technical articles for a french magazine, several times, didn't get stoned for them, guess they were not too bad (@26, and @27)"
  - "I've cooked vegeterian meals for 100+ people and 30+ Buddhist monks with extra care (@26)"
  - "I've cut and soldered pvc and PPE above chromium acid and cyanide tanks, and then walked my way in other strong chemical environments (@27)"
  - "I went to walk around in Kathmandu and managed to cut my foot while walking up a fly of stairs, got stitches, accused of being a drug addict (while being stitched) and got a nice visit from the Nepali army for that (@27)"
  - "I went back to IT and my ex girlfriends Ruby and Deb who welcomed me with open arms (@27)"
  - "I've created my own company to live from Ruby and OpenSource projects and systems (@27, about time !)"
  - "Consulting while trying to make a nice product or get in a nice company or just work on my own simply (@28)"